[project]
name = "tstickers"
version = "2026"
description = "Download sticker packs from Telegram"
authors = [{ name = "FredHappyface" }]
requires-python = ">=3.10"
readme = "README.md"
license = "mit"
classifiers = [
	"Development Status :: 5 - Production/Stable",
	"Intended Audience :: Developers",
	"Intended Audience :: Education",
	"Natural Language :: English",
	"Operating System :: OS Independent",
	"Programming Language :: Python :: Implementation :: CPython",
	"Topic :: Software Development :: Libraries :: Python Modules",
	"Topic :: Utilities",
	"Topic :: Multimedia :: Graphics",
]
dependencies = [
    "emoji>=2.15.0",
    "loguru>=0.7.3",
    "pillow>=12.1.0",
    "requests>=2.32.5",
    "requests-cache>=1.3.0",
    "rlottie-python>=1.3.8",
]


[project.urls]
Homepage = "https://github.com/FHPythonUtils/TStickers"
Repository = "https://github.com/FHPythonUtils/TStickers"
Documentation = "https://github.com/FHPythonUtils/TStickers/blob/master/README.md"

[project.scripts]
tstickers = "tstickers:cli"

[dependency-groups]
dev = [
    "coverage>=7.13.3",
    "prek>=0.3.1",
    "basedpyright>=1.37.4",
    "pytest>=9.0.2",
    "ruff>=0.15.0",
]

[tool.ruff]
line-length = 100
indent-width = 4
target-version = "py38"

[tool.ruff.lint]
select = ["ALL"]
ignore = [
	"COM812", # enforce trailing comma
	"D2",     # pydocstyle formatting
	"ISC001",
	"N",      # pep8 naming
	"PLR09",  # pylint refactor too many
	"TCH",    # type check blocks
	"W191",   # ignore this to allow tabs
	"PLR2004", # Magic value used in comparison,
]
fixable = ["ALL"]

[tool.ruff.lint.per-file-ignores]
"**/{tests,docs,tools}/*" = ["D", "S101", "E402"]

[tool.ruff.lint.flake8-tidy-imports]
ban-relative-imports = "all" # Disallow all relative imports.

[tool.ruff.format]
indent-style = "tab"
docstring-code-format = true
line-ending = "lf"

[tool.pyright]
venvPath = "."
venv = ".venv"

typeCheckingMode = "basic"

reportMissingImports = "error"
reportMissingTypeStubs = false

pythonVersion = "3.10"


[tool.coverage.run]
branch = true

[tool.tox]
legacy_tox_ini = """
[tox]
env_list =
	py313
	py312
	py311
	py310
	py39

[testenv]
deps =
	pytest
commands = pytest tests
"""

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
